eureka:
  client:
    service-url:
      defaultZone: https://eurekaserver.perseidas.dev/eureka/
management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info 
info:
  author: Ronilson Alves
  mail: falecom@ronilsonalves.com
server:
  port: ${PORT:8080}
message: Genereci Config
