eureka:
  client:
    service-url:
      #defaultZone: https://eurekaserver.perseidas.dev/eureka
      defaultZone: https://springeurekaserver.azurewebsites.net/eureka

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info 

info:
  author: Ronilson Alves
  mail: falecom@ronilsonalves.com
server:
  port: ${PORT:8091}
message: Generec Config

spring:
  cloud:
    ineutils:
      #default-hostname: https://eurekaserver.perseidas.dev
      timeout-seconds: 10
logging:
  level:
    org.springframework.cloud.commons.util.InetUtils: trace
